---
# Source: ingressmonitorcontroller/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ingressmonitorcontroller
    version: 1.0.23
    group: com.stakater.platform
    provider: stakater
    chart: "ingressmonitorcontroller-1.0.23"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: ingressmonitorcontroller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: ingressmonitorcontroller-role
  namespace: "default"
rules:
  - apiGroups:
      - ""
      - "extensions"
    resources:
      - ingresses
    verbs:
      - list
      - get
      - update
      - patch
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - services
      - pods
    verbs:
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ingressmonitorcontroller-role-binding
  namespace: "default"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingressmonitorcontroller-role
subjects:
  - kind: ServiceAccount
    name: ingressmonitorcontroller
    namespace: "tools"
