apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/target-platform: kubernetes
  labels:
    provider: stakater
    project: ingress-monitor-controller
    version: 1.0.0
  name: ingress-monitor-controller
data:
  config.yaml: |-
    providers: 
    - name: UptimeRobot
      apiKey: your-api-key
      apiURL: https://api.uptimerobot.com/v2/
      alertContacts: "0544483_0_0-2628365_0_0-2633263_0_0"
    enableMonitorDeletion: true