apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ingress-monitor-controller
    group: com.stakater.platform
    version: 0.2.8
    provider: stakater
  name: ingressmonitorcontroller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: ingress-monitor-controller
    group: com.stakater.platform
    version: 0.2.8
    provider: stakater
  name: ingressmonitorcontroller-role
rules:
  - apiGroups:
      - ""
      - "extensions"
    resources:
      - ingresses
    verbs:
      - list
      - get
      - update
      - patch
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - list
      - get
      - update
      - patch
      - watch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: ingress-monitor-controller
    group: com.stakater.platform
    version: 0.2.8
    provider: stakater
  name: ingressmonitorcontroller-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingressmonitorcontroller-role
subjects:
  - kind: ServiceAccount
    name: ingressmonitorcontroller
    namespace: dev