apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "name" . }}
    version: {{ .Chart.Version }}
    group: {{ .Values.ingressMonitorController.labels.group }}
    provider: {{ .Values.ingressMonitorController.labels.provider }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  name: {{ template "name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "name" . }}-role
  {{ if .Values.ingressMonitorController.watchNamespace }}
  namespace: {{ .Values.ingressMonitorController.watchNamespace | quote }}
  {{ end }}
rules:
  - apiGroups:
      - ""
      - "extensions"
    resources:
      - ingresses
    verbs:
      - list
      - get
      - update
      - patch
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - services
      - pods
    verbs:
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "name" . }}-role-binding
  {{ if .Values.ingressMonitorController.watchNamespace }}
  namespace: {{ .Values.ingressMonitorController.watchNamespace | quote }}
  {{ end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "name" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ template "name" . }}
    namespace: {{ .Release.Namespace | quote }}
