---
# Source: ingress-monitor-controller/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/target-platform: kubernetes
  labels:
    app: RELEASE-NAME-ingress-monitor-controller
    chart: "ingress-monitor-controller-0.2.12"
    release: "RELEASE-NAME"
    heritage: "Tiller"
    project: ingress-monitor-controller
  name: ingress-monitor-controller
data:
  config.yaml: |-
    providers:
    - name: UptimeRobot
      apiKey: your-api-key
      apiURL: https://google.com
      alertContacts: some-alert-contacts
    enableMonitorDeletion: true
    monitorNameTemplate: "{{.Namespace}}-{{.IngressName}}"
