---
# Source: IngressMonitorController/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/target-platform: kubernetes
  labels:
    app: IngressMonitorController
    chart: "IngressMonitorController-0.2.15"
    release: "RELEASE-NAME"
    heritage: "Tiller"
    project: IngressMonitorController
  name: IngressMonitorController
data:
  config.yaml: |-
    providers:
    - name: UptimeRobot
      apiKey: your-api-key
      apiURL: https://google.com
      alertContacts: some-alert-contacts
    enableMonitorDeletion: true
    monitorNameTemplate: "{{.Namespace}}-{{.IngressName}}"
