---
# Source: IngressMonitorController/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.fabric8.io/update-on-change: ingressmonitorcontroller
  labels:
    app: ingressmonitorcontroller
    version: 1.0.5
    group: 
    provider: 
    chart: "IngressMonitorController-1.0.5"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: ingressmonitorcontroller
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ingressmonitorcontroller
      version: 1.0.5
      group: 
      provider: 
  template:
    metadata:
      annotations:
        configmap.fabric8.io/update-on-change: ingressmonitorcontroller
      labels:
        app: ingressmonitorcontroller
        version: 1.0.5
        group: 
        provider: 
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_FILE_PATH
          value: /etc/IngressMonitorController/config.yaml
        image: "stakater/ingressmonitorcontroller:1.0.5"
        imagePullPolicy: IfNotPresent
        name: ingressmonitorcontroller
        volumeMounts:
        - mountPath: /etc/IngressMonitorController
          name: config-volume
      serviceAccountName: ingressmonitorcontroller
      volumes:
      - configMap:
          name: ingressmonitorcontroller
        name: config-volume
