---
# Source: ingress-monitor-controller/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.fabric8.io/update-on-change: ingress-monitor-controller
  labels:
    app: RELEASE-NAME-ingress-monitor-controller
    chart: "ingress-monitor-controller-0.2.11"
    release: "RELEASE-NAME"
    heritage: "Tiller"
    project: ingress-monitor-controller
  name: ingress-monitor-controller
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      annotations:
        configmap.fabric8.io/update-on-change: ingress-monitor-controller
      labels:
        app: RELEASE-NAME-ingress-monitor-controller
        chart: "ingress-monitor-controller-0.2.11"
        release: "RELEASE-NAME"
        heritage: "Tiller"
        project: ingress-monitor-controller
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_FILE_PATH
          value: /etc/ingress-monitor-controller/config.yaml
        image: "stakater/ingress-monitor-controller:0.2.11"
        imagePullPolicy: IfNotPresent
        name: ingress-monitor-controller
        volumeMounts:
        - mountPath: /etc/ingress-monitor-controller
          name: config-volume
      serviceAccountName: ingress-monitor-controller
      volumes:
      - configMap:
          name: ingress-monitor-controller
        name: config-volume
