---
# Source: IngressMonitorController/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.fabric8.io/update-on-change: ingressmonitorcontroller
  labels:
    app: ingressmonitorcontroller
    chart: "IngressMonitorController-1.0.3"
    release: "RELEASE-NAME"
    heritage: "Tiller"
    project: ingressmonitorcontroller
  name: ingressmonitorcontroller
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      annotations:
        configmap.fabric8.io/update-on-change: ingressmonitorcontroller
      labels:
        app: ingressmonitorcontroller
        chart: "IngressMonitorController-1.0.3"
        release: "RELEASE-NAME"
        heritage: "Tiller"
        project: ingressmonitorcontroller
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_FILE_PATH
          value: /etc/IngressMonitorController/config.yaml
        image: "stakater/ingressmonitorcontroller:1.0.3"
        imagePullPolicy: IfNotPresent
        name: ingressmonitorcontroller
        volumeMounts:
        - mountPath: /etc/IngressMonitorController
          name: config-volume
      serviceAccountName: ingressmonitorcontroller
      volumes:
      - configMap:
          name: ingressmonitorcontroller
        name: config-volume
