---
# Source: ingress-monitor-controller/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: RELEASE-NAME-ingress-monitor-controller
    chart: "ingress-monitor-controller-0.2.10"
    release: "RELEASE-NAME"
    heritage: "Tiller"
    project: ingress-monitor-controller
    group: com.stakater
  name: ingress-monitor-controller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: ingress-monitor-controller-role
rules:
  - apiGroups:
      - ""
      - "extensions"
    resources:
      - ingresses
    verbs:
      - list
      - get
      - update
      - patch
      - watch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ingress-monitor-controller-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-monitor-controller-role
subjects:
  - kind: ServiceAccount
    name: ingress-monitor-controller
    namespace: default
